### ISSUE TITLE
Configurando o build

### ISSUE THREAD

**Issue by danilodamasceno** [Processos-de-software-2016-2/Infraestrutura#13]

**Comment by ghost** [comment]
A ideia dessa issue é que alguém crie o passo a passo para subir os ambientes.
Por exemplo, no caso da API, seria que o Travis execute os comandos para a aplicação rodar. (gunicorn main:app --bind 0.0.0.0:<desired_port>)

**Comment by ghost** [comment]
Pronto, já configurei tudo.
