### ISSUE TITLE
Comunicação Externa 

### ISSUE THREAD

**Issue by danilodamasceno** [Processos-de-software-2016-2/Infraestrutura#9]
Comunicar o serviço API - DOCKER com o meio externo para acesso de dados pelo APP - MOBILE

**Comment by danilodamasceno** [comment]
regra no arquivos /etc/services adicionada porém ainda nao funcionando.
regra: api-python 8000/tcp

**Comment by wreuel** [comment]
Comando para verificar a funcionalidade
nc -zv 127.0.0.1 8000

outro modo de adicionar a regra
 sudo iptables -A INPUT -p tcp --dport 8000 -j ACCEPT

Tutorial da própria DigitalOcean utilizado:
https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-using-iptables-on-ubuntu-14-04

**Comment by danilodamasceno** [comment]
Testes realizados, comunicação externa funcionando normal.
